_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
e:
    value: 50
fp:
    value: null
h:
    value: 32
id:
    value: exp2
k:
    value: 1
mode:
    value: train
"n":
    value: 4
s:
    value: 1000
test_chkpt:
    value: null
test_file:
    value: null
train_file:
    value: ./data/train_4x4.npy
train_it:
    value: 100000
val_file:
    value: ./data/val_4x4.npy
val_it:
    value: 20000
